CREATE TABLE users (
  user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(256) NOT NULL,
  PASSWORD VARCHAR(256) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL

);

CREATE TABLE  roles (
  role_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256) NOT NULL
);

CREATE TABLE markers (
  marker_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(256) NOT NULL,
  LAT DOUBLE NOT NULL DEFAULT 0,
  LNG DOUBLE NOT NULL DEFAULT 0,
  INFO VARCHAR(256) NOT NULL,
  user_id BIGINT,
  FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE  users_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
CONSTRAINT role_fk FOREIGN KEY (role_id) REFERENCES roles (role_id),
CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES users (user_id)
);
