CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(256) NOT NULL,
  PASSWORD VARCHAR(256) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL
);





CREATE TABLE IF NOT EXISTS markers(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(256) NOT NULL,
  LAT         DOUBLE NOT NULL DEFAULT 0,
  LNG         DOUBLE NOT NULL DEFAULT 0,
  INFO VARCHAR(256) NOT NULL,
  user_id BIGINT,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
